apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-tracker

resources:
  - ../ai-eng

patches:
  - path: route-patch.yaml
  - path: api-route-patch.yaml

configMapGenerator:
  - name: team-tracker-config
    behavior: merge
    literals:
      - ADMIN_EMAILS=
