apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../ai-eng

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  - AUTH_EMAIL_DOMAIN=cluster.local
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: 585052d19f09ae91fb9d0d5b1c797bf2688cbd13
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: 5f48219231fa4a578867c1d18e3bceaabde7e7e5
