apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../../base
- cronjob-sync-refresh.yaml

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: f4564ca068fe56f0d283429c99c4f51a913dad29
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: f4564ca068fe56f0d283429c99c4f51a913dad29
