import {
  BarChart3,
  Box,
  Briefcase,
  Building2,
  Factory,
  PackageOpen,
  ChartColumnStacked,
  FolderOpen,
  FolderTree,
  Lightbulb,
  Map,
  Milestone,
  Target,
  UserCog,
  Users,
  UsersRound,
  User,
  TrendingUp,
  FileText,
  Home,
  Shield,
  Settings,
  ExternalLink,
  Network,
  Layers,
  Sparkles,
  Activity,
  Wand2,
  ClipboardList,
  BookOpen,
  Database,
  History,
  Hospital,
  LayoutDashboard,
  Rocket,
  UserCircle,
  CalendarDays,
  ChartCandlestick,
  PieChart,
  GitBranch
} from 'lucide-vue-next'

export const ICON_MAP = {
  BarChart3,
  Box,
  Briefcase,
  Building2,
  Factory,
  PackageOpen,
  ChartColumnStacked,
  FolderOpen,
  FolderTree,
  Lightbulb,
  Map,
  Milestone,
  Target,
  UserCog,
  Users,
  UsersRound,
  User,
  TrendingUp,
  FileText,
  Home,
  Shield,
  Settings,
  ExternalLink,
  Network,
  Layers,
  Sparkles,
  Activity,
  Wand2,
  'bar-chart': BarChart3,
  'users-round': UsersRound,
  'chart-candlestick': ChartCandlestick,
  'pie-chart': PieChart,
  'git-branch': GitBranch,
  'sparkles': Sparkles,
  'activity': Activity,
  'network': Network,
  'clipboard-list': ClipboardList,
  BookOpen,
  ClipboardList,
  Database,
  History,
  Hospital,
  'hospital': Hospital,
  CalendarDays,
  LayoutDashboard,
  Rocket,
  UserCircle,
  'rocket': Rocket
}

export function resolveIcon(iconName) {
  return ICON_MAP[iconName] || BarChart3
}
